# Generated by Django 5.2.8 on 2025-11-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('fixed', 'Фіксована'), ('bonus', 'З бонусами')], max_length=20)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('department', models.CharField(max_length=100, verbose_name='Відділ')),
                ('hire_date', models.DateField(verbose_name='Дата найму')),
                ('salary_strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.salarystrategy', verbose_name='Стратегія зарплати')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
            },
        ),
    ]
