# Generated by Django 5.2.8 on 2026-01-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSalaryStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова зарплата')),
                ('bonus_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Відсоток бонусу')),
            ],
            options={
                'verbose_name': 'Стратегія: З бонусами',
                'verbose_name_plural': 'Стратегії: З бонусами',
            },
        ),
        migrations.CreateModel(
            name='FixedSalaryStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Місячна сума')),
            ],
            options={
                'verbose_name': 'Стратегія: Фіксована',
                'verbose_name_plural': 'Стратегії: Фіксовані',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('department', models.CharField(max_length=100, verbose_name='Відділ')),
                ('hire_date', models.DateField(verbose_name='Дата найму')),
                ('salary_strategy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_strategy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип стратегії')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
            },
        ),
        migrations.CreateModel(
            name='ReportsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Звіти та аналітика',
                'verbose_name_plural': 'Звіти та аналітика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
    ]
