# Generated by Django 5.2.8 on 2025-11-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Контракт'), ('leave_request', 'Заявка на відпустку')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Співробітник')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='documents.document')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракти',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Відпустка'), ('sick', 'Лікарняний')], max_length=20, verbose_name='Тип')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request', to='documents.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Співробітник')),
            ],
            options={
                'verbose_name': 'Заявка на відпустку',
                'verbose_name_plural': 'Заявки на відпустку',
            },
        ),
    ]
