# Generated by Django 5.2.8 on 2026-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракти',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Відпустка'), ('sick', 'Лікарняний')], max_length=20, verbose_name='Тип')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на відпустку',
                'verbose_name_plural': 'Заявки на відпустку',
            },
        ),
    ]
