# Generated by Django 5.2.8 on 2025-11-27 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва вакансії')),
                ('department', models.CharField(max_length=100, verbose_name='Відділ')),
                ('description', models.TextField(verbose_name='Опис')),
                ('requirements', models.TextField(verbose_name='Вимоги')),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата від')),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('vacation', 'Наказ про відпустку'), ('hire', 'Наказ про прийняття на роботу'), ('fire', 'Наказ про звільнення'), ('promotion', 'Наказ про підвищення')], max_length=20, verbose_name='Тип наказу')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер наказу')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('content', models.TextField(verbose_name='Зміст наказу')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Співробітник')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('resume', models.TextField(verbose_name='Резюме/Досвід')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('interview', 'На співбесіді'), ('offer', 'Оффер надіслано'), ('hired', 'Прийнято'), ('rejected', 'Відхилено')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки HR')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.vacancy', verbose_name='Вакансія')),
            ],
        ),
    ]
