# Generated by Django 5.2.8 on 2026-01-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва посади')),
                ('department', models.CharField(max_length=100, verbose_name='Відділ')),
                ('description', models.TextField(verbose_name='Опис вакансії')),
                ('requirements', models.TextField(verbose_name='Вимоги')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата від')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('status', models.CharField(choices=[('open', 'Відкрита'), ('closed', 'Закрита'), ('on_hold', 'На паузі')], default='open', max_length=20, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('resume', models.TextField(blank=True, verbose_name='Резюме')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Супровідний лист')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('screening', 'Скринінг'), ('interview', 'Співбесіда'), ('offer', 'Оффер'), ('hired', 'Прийнятий'), ('rejected', 'Відхилений')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки HR')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подання')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.vacancy', verbose_name='Вакансія')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидати',
                'ordering': ['-applied_date'],
            },
        ),
    ]
