# Generated by Django 5.2.8 on 2026-01-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_vacancy_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидати'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансія', 'verbose_name_plural': 'Вакансії'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('review', 'На розгляді'), ('interview', 'Співбесіда'), ('offer', 'Оффер'), ('hired', 'Прийнятий'), ('rejected', 'Відхилений')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата від'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата до'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], default='approved', max_length=20, verbose_name='Статус'),
        ),
    ]
