# Generated by Django 5.2.8 on 2025-11-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_type', models.CharField(choices=[('pending', 'Очікує подання'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], max_length=20)),
            ],
            options={
                'verbose_name': 'Стан заявки',
                'verbose_name_plural': 'Стани заявок',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Співробітник')),
                ('current_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.requeststate', verbose_name='Поточний стан')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
