# Generated by Django 5.2.8 on 2026-01-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Стан: Схвалено',
                'verbose_name_plural': 'Стани: Схвалені',
            },
        ),
        migrations.CreateModel(
            name='PendingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Стан: Очікує',
                'verbose_name_plural': 'Стани: Очікують',
            },
        ),
        migrations.CreateModel(
            name='RejectedState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Стан: Відхилено',
                'verbose_name_plural': 'Стани: Відхилені',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('remote', 'Віддалена робота'), ('other', 'Інше')], default='vacation', max_length=20, verbose_name='Тип заявки')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('hr_comment', models.TextField(blank=True, verbose_name='Коментар HR')),
                ('current_state_id', models.PositiveIntegerField(blank=True, null=True)),
                ('current_state_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип стану')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Співробітник')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_date'],
            },
        ),
    ]
