# Generated by Django 5.2.8 on 2025-11-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AddField(
            model_name='request',
            name='hr_comment',
            field=models.TextField(blank=True, verbose_name='Коментар HR'),
        ),
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина/Опис'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('remote', 'Віддалена робота'), ('other', 'Інше')], default='vacation', max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='requeststate',
            name='state_type',
            field=models.CharField(choices=[('pending', 'Очікує розгляду'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], max_length=20, unique=True, verbose_name='Тип стану'),
        ),
    ]
