# Generated by Django 5.2.8 on 2025-11-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(verbose_name='Час входу')),
                ('clock_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Час виходу')),
                ('date', models.DateField(verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Співробітник')),
            ],
            options={
                'verbose_name': 'Запис робочого часу',
                'verbose_name_plural': 'Записи робочого часу',
                'ordering': ['-date', '-clock_in_time'],
            },
        ),
    ]
