# Generated by Django 5.2.8 on 2025-11-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Створено замовлення'), ('order_status', 'Зміна статусу замовлення'), ('leave_approved', 'Відпустку схвалено'), ('leave_rejected', 'Відпустку відхилено')], max_length=50, verbose_name='Тип сповіщення')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='push', max_length=20, verbose_name='Канал')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Надіслано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Одержувач')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
    ]
